blueprint:
  name: Interval Power Cycle
  description: Turn a device based on a timed interval
  domain: automation
  source_url: https://github.com/darkxst/hascripts/blob/main/config/blueprints/automation/dialed_lights_bp.yaml
  input:
    duration:
      name: Duration
      description: Length of runtime
      selector:
        entity:
          domain: input_number
    interval:
      name: Interval
      description: cycle time
      selector:
        entity:
          domain: input_number
    condition_entity:
      name: Condition
      description: Only run if entity ID is currently active (Optional)
      default: {}
      selector:
        entity:
          domain:
            - switch
            - input_boolean
    fan_id:
      name: Device(s)
      description: Device to control
      selector:
        target:
          entity:
            domain:
              - switch
              - input_boolean
variables:
  duration: !input duration
  condition_entity: !input condition_entity
  fan: !input fan_id
  fan_list: "{{ [fan.entity_id] if fan.entity_id is string else fan.entity_id }}"
trigger_variables:
  interval: !input interval
trigger:
  - platform: template
    value_template: "{{ now().minute % states(interval)|int == 0  }}"

condition:
  - condition: or
    conditions:
      - "{{ condition_entity | length == 0 }}"
      - "{{ states(condition_entity) == 'on' }}"

action:
  - repeat:
      for_each: "{{ fan_list }}"
      sequence:
        - service: >
            {{ states[repeat.item].domain ~ '.turn_on' }}
          target:
            entity_id: "{{ repeat.item }}"
  - delay: "{{ states(duration) | int * 60 }}"
  - repeat:
      for_each: "{{ fan_list }}"
      sequence:
        - service: >
            {{ states[repeat.item].domain ~ '.turn_off' }}
          target:
            entity_id: "{{ repeat.item }}"